name: Label PR based on Review Urgency
on:
  pull_request:
    types: [opened, edited]

jobs:
  labelPR:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract urgency and add labels
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'edited' }}
        run: |
          bodyText=$(echo "${{ github.event.pull_request.body }}")
          urgency=$(echo "$bodyText" | grep -o 'D-[0-9]')
          echo "Urgency: $urgency"
          
          if [ -n "$urgency" ]; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label $urgency
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
