name: Label PR based on Review Urgency
on:
  pull_request:
    types: [opened, edited]

jobs:
  labelPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract urgency from PR body
        id: extract-urgency
        run: |
          bodyText=$(echo "${{ github.event.pull_request.body }}")
          urgency=$(echo "$bodyText" | grep -o 'D-[0-9]')
          echo "Urgency: $urgency"
          echo "::set-output name=urgency::$urgency"

      - name: add labels
        if: steps.extract-urgency.outputs.urgency != ''
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label ${{ steps.extract-urgency.outputs.urgency }}
