name: Label PR based on Review Urgency
on:
  pull_request:
    types: [opened, edited]

jobs:
  labelPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find and add label
        run: |
          echo ${{ github.event.comment.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
