name: Label PR based on d-day
on:
  pull_request:
    types: [opened, edited]

jobs:
  labelPR:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract d-day and add labels
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'edited' }}
        run: |
          bodyText=$(echo "${{ github.event.pull_request.body }}")
          dDay=$(echo "$bodyText" | grep -o 'D-[0-9]')
          echo "d-day: $dDay"
          
          if [ -n "$dDay" ]; then
            labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
            labelExists=$(echo "$labels" | grep -o "$dDay")
      
            if [ -z "$labelExists" ]; then
              gh label create "$dDay"
            fi
      
            gh pr edit ${{ github.event.pull_request.number }} --add-label "$dDay"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
