name: Label PR based on d-day
on:
  pull_request:
    types: [opened, edited]

jobs:
  labelPR:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add or Remove D-Day Label
        if: ${{ github.event.action == 'opened' || github.event.action == 'edited' }}
        run: |
          bodyText=$(echo "${{ github.event.pull_request.body }}")
          dDay=$(echo "$bodyText" | grep -o 'D-[0-5]')
          echo "d-day: $dDay"
          
          if [ -n "$dDay" ]; then
            gh pr edit ${{ github.event.pull_request.number }} --remove-label 'D-[0-5]' --add-label $dDay
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
