name: PR Title Lint

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          BRANCH_TITLE_PATTERN='^\[([A-Z]+-[0-9]+|NO-JIRA)\] .+$'
          MAIN_BRANCH_TITLE_PATTERN='^v[0-9]{12}$'

          if [[ "${TARGET_BRANCH}" == "main" ]]; then
            PATTERN="${MAIN_BRANCH_TITLE_PATTERN}"
          else
            PATTERN="${BRANCH_TITLE_PATTERN}"
          fi

          if [[ ! "${PR_TITLE}" =~ ${PATTERN} ]]; then
            echo -e "PR Title이 올바르지 않습니다.\nex) [NO-JIRA] PR Title, [JIRA-123] PR Title or v202308301300"
            exit 1
          else
            echo "Pass."
          fi
